version: "3.7"
services:

  frontend:
    image: warsawlo/warsawlo-2.0:latest
    ports:
      - "80:80"
    networks:
      - warsawlo
    environment:
      NGINX_BACK_URL: "backend:8080"
      NGINX_SERVER_NAME: "localhost 127.0.0.1"
      API_URL: "/api"
      PUBLIC_SENTRY_DSN: ""
    env_file:
      - local.env
    depends_on:
      - backend

  backend:
    image: warsawlo/warsawlo-django:latest
    volumes:
      - media:/opt/warsawlo/media
    networks:
      - warsawlo
    environment:
      DJANGO_SETTINGS_MODULE: warsawlo.settings
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1"
      SECURE_COOKIES: "True"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: warsawlo
      SQL_USER: warsawlo
      SQL_PASSWORD: warsawlo
      SQL_HOST: "db"
      UWSGI_WORKERS_COUNT: 1
    env_file:
      - local.env
    depends_on:
      - db

  db:
    image: postgres:12.2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: warsawlo
      POSTGRES_PASSWORD: warsawlo
      POSTGRES_DB: warsawlo
    networks:
      - warsawlo

networks:
  warsawlo:

volumes:
  db-data:
  media:
