# Generated by Django 3.0 on 2019-12-16 21:46

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='^\\d\\d-\\d\\d\\d$')])),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building_nr', models.CharField(max_length=20)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=100, null=True, verbose_name=django.core.validators.EmailValidator())),
            ],
        ),
        migrations.CreateModel(
            name='PublicInstitutionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_short_name', models.CharField(max_length=20)),
                ('institution_type', models.CharField(max_length=100)),
                ('institution_nr', models.CharField(max_length=20)),
                ('institution_RSPO', models.CharField(max_length=20)),
                ('RSPO', models.CharField(max_length=20)),
                ('institution_regon', models.CharField(max_length=14)),
                ('regon', models.CharField(max_length=14)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_type', models.CharField(max_length=100)),
                ('school_type_generalised', models.CharField(max_length=40)),
                ('student_type', models.CharField(max_length=100)),
                ('is_special_needs_school', models.BooleanField(default=False)),
                ('specialised_divisions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Address')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.ContactData')),
                ('public_institution_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.PublicInstitutionData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_type', models.CharField(max_length=100)),
                ('school_type_generalised', models.CharField(max_length=40)),
                ('student_type', models.CharField(max_length=100)),
                ('is_special_needs_school', models.BooleanField(default=False)),
                ('specialised_divisions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('registration_nr', models.CharField(max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Address')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.ContactData')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
