# Generated by Django 3.0.1 on 2020-01-24 17:20

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_insert_niepubliczne_technikum_mlodziez'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('school_id', models.CharField(max_length=100)),
                ('year', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('points_min', models.FloatField()),
                ('points_max', models.FloatField()),
                ('points_avg', models.FloatField()),
                ('with_competency_test', models.BooleanField(default=False)),
                ('only_sports_test', models.BooleanField(default=False)),
                ('high_school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.HighSchoolClass')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ang', 'język angielski'), ('franc', 'język francuski'), ('hiszp', 'język hiszpański'), ('niem', 'język niemiecki'), ('ros', 'język rosyjski'), ('wło', 'język włoski'), ('antyk', 'język łaciński i kultura antyczna'), ('język białoruski', 'język białoruski'), ('język litewski', 'język litewski'), ('język ukraiński', 'język ukraiński'), ('język łemkowski', 'język łemkowski'), ('język kaszubski', 'język kaszubski')], max_length=40)),
                ('nr', models.IntegerField(choices=[(1, 'pierwszy'), (2, 'drugi')])),
                ('is_bilingual', models.BooleanField(default=False)),
                ('multiple_levels', models.BooleanField(default=False)),
                ('high_school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.HighSchoolClass')),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('biol', 'biologia'), ('chem', 'chemia'), ('filoz', 'filozofia'), ('fiz', 'fizyka'), ('geogr', 'geografia'), ('hist', 'historia'), ('h.muz.', 'historia muzyki'), ('h.szt.', 'historia sztuki'), ('inf', 'informatyka'), ('pol', 'język polski'), ('mat', 'matematyka'), ('wos', 'wiedza o społeczeństwie'), ('obcy', 'obcy'), ('ang', 'język angielski'), ('franc', 'język francuski'), ('hiszp', 'język hiszpański'), ('niem', 'język niemiecki'), ('ros', 'język rosyjski'), ('wło', 'język włoski'), ('antyk', 'język łaciński i kultura antyczna'), ('język białoruski', 'język białoruski'), ('język litewski', 'język litewski'), ('język ukraiński', 'język ukraiński'), ('język łemkowski', 'język łemkowski'), ('język kaszubski', 'język kaszubski')], max_length=40)),
                ('high_school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.HighSchoolClass')),
            ],
        ),
    ]
