# Generated by Django 3.0.1 on 2020-01-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_insert_profile_publiczne_lo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschoolclass',
            name='school_id',
            field=models.IntegerField(),
        ),
    ]
