# Generated by Django 3.0.1 on 2020-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_alter_highschoolclass_school_id_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateschool',
            name='nickname',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicschool',
            name='nickname',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
