# Generated by Django 3.0.7 on 2020-08-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0010_auto_20200822_2142"),
    ]

    operations = [
        migrations.RenameField("Address", "longitude", "true_latitude"),
        migrations.RenameField("Address", "latitude", "longitude"),
        migrations.RenameField("Address", "true_latitude", "latitude"),
    ]
