# Generated by Django 3.0.1 on 2020-02-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_alter_school_add_nickname'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX "search_publicschool_name_idx" '
            'ON "search_publicschool" '
            'USING GIN (school_name gin_trgm_ops);',
            reverse_sql='DROP INDEX "search_publicschool_name_idx";',
        ),
        migrations.RunSQL(
            'CREATE INDEX "search_publicschool_nickname_idx" '
            'ON "search_publicschool" '
            'USING GIN (nickname gin_trgm_ops);',
            reverse_sql='DROP INDEX "search_publicschool_nickname_idx";',
        ),
        migrations.RunSQL(
            'CREATE INDEX "search_privateschool_name_idx" '
            'ON "search_privateschool" '
            'USING GIN (school_name gin_trgm_ops);',
            reverse_sql='DROP INDEX "search_privateschool_name_idx";',
        ),
        migrations.RunSQL(
            'CREATE INDEX "search_privateschool_nickname_idx" '
            'ON "search_privateschool" '
            'USING GIN (nickname gin_trgm_ops);',
            reverse_sql='DROP INDEX "search_privateschool_nickname_idx";',
        )
    ]
