# Generated by Django 3.0.7 on 2021-04-17 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0014_auto_20210416_2111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactdata",
            name="email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name=django.core.validators.EmailValidator(),
            ),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="contactdata",
            name="website",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="RSPO",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="institution_RSPO",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="institution_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="institution_nr",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="institution_regon",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="institution_short_name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="institution_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="regon",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name="publicinstitutiondata",
            name="short_name",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
