# Generated by Django 3.0.7 on 2021-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0015_auto_20210417_1157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extendedsubject",
            name="name",
            field=models.CharField(
                choices=[
                    ("biol", "biologia"),
                    ("chem", "chemia"),
                    ("filoz", "filozofia"),
                    ("fiz", "fizyka"),
                    ("geogr", "geografia"),
                    ("hist", "historia"),
                    ("h.muz.", "historia muzyki"),
                    ("h.szt.", "historia sztuki"),
                    ("inf", "informatyka"),
                    ("pol", "język polski"),
                    ("mat", "matematyka"),
                    ("wos", "wiedza o społeczeństwie"),
                    ("obcy", "język obcy"),
                    ("ang", "język angielski"),
                    ("fra", "język francuski"),
                    ("hisz", "język hiszpański"),
                    ("niem", "język niemiecki"),
                    ("por", "język portugalski"),
                    ("ros", "język rosyjski"),
                    ("wlo", "język włoski"),
                    ("antyk", "język łaciński i kultura antyczna"),
                    ("język białoruski", "język białoruski"),
                    ("język litewski", "język litewski"),
                    ("język ukraiński", "język ukraiński"),
                    ("język łemkowski", "język łemkowski"),
                    ("język kaszubski", "język kaszubski"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="highschoolclass",
            name="type",
            field=models.CharField(
                choices=[
                    ("ogólnodostępny", "O"),
                    ("mistrzostwa sportowego", "Ms"),
                    ("dwujęzyczny", "D"),
                    ("międzynarodowy", "M"),
                    ("wstępny", "Dw"),
                    ("sportowy", "S"),
                    ("integracyjny cz. ogólnodostępna", "Io"),
                    (
                        "integracyjny cz. dla kandydatów z orzeczeniem o potrzebie kształcenia specjalnego",
                        "Ii",
                    ),
                    ("przygotowania wojskowego", "Pw"),
                ],
                max_length=81,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                choices=[
                    ("ang", "język angielski"),
                    ("fra", "język francuski"),
                    ("hisz", "język hiszpański"),
                    ("niem", "język niemiecki"),
                    ("por", "język portugalski"),
                    ("ros", "język rosyjski"),
                    ("wlo", "język włoski"),
                    ("antyk", "język łaciński i kultura antyczna"),
                    ("język białoruski", "język białoruski"),
                    ("język litewski", "język litewski"),
                    ("język ukraiński", "język ukraiński"),
                    ("język łemkowski", "język łemkowski"),
                    ("język kaszubski", "język kaszubski"),
                ],
                max_length=40,
            ),
        ),
    ]
