# Generated by Django 3.0.7 on 2021-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0016_auto_20210417_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highschoolclass",
            name="type",
            field=models.CharField(
                choices=[
                    ("O", "ogólnodostępny"),
                    ("MS", "mistrzostwa sportowego"),
                    ("D", "dwujęzyczny"),
                    ("M", "międzynarodowy"),
                    ("DW", "wstępny"),
                    ("S", "sportowy"),
                    ("I-o", "integracyjny cz. ogólnodostępna"),
                    (
                        "I-i",
                        "integracyjny cz. dla kandydatów z orzeczeniem o potrzebie kształcenia specjalnego",
                    ),
                    ("PW", "przygotowania wojskowego"),
                ],
                max_length=3,
            ),
        ),
    ]
