# Generated by Django 3.0.7 on 2021-06-15 14:25

from django.db import migrations

from search.models import LanguageName


def forwards_func(apps, schema):
    Language = apps.get_model("search", "Language")

    Language.objects.filter(name="franc").update(name=LanguageName.FRA[0])
    Language.objects.filter(name="hiszp").update(name=LanguageName.HISZ[0])


def reverse_func(apps, schema):
    Language = apps.get_model("search", "Language")

    Language.objects.filter(name=LanguageName.FRA[0]).update(name="franc")
    Language.objects.filter(name=LanguageName.HISZ[0]).update(name="hiszp")


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0019_insert_scores_2020"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
